<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Notification</name>
   <tag></tag>
   <elementGuidId>07fa9b10-61b3-41fa-b8d3-2b836954c1d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Featured Articles']/div/div[2]/ir-header-icons/ul/modal-email-alert/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Featured Articles&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 text-right&quot;]/ir-header-icons[1]/ul[@class=&quot;actionSetting&quot;]/modal-email-alert[1]/li[@class=&quot;notify&quot;][count(. | //li[@class = 'notify' and @placement = 'bottom' and @tooltip = 'Notification' and @aria-describedby = 'tooltip-16']) = count(//li[@class = 'notify' and @placement = 'bottom' and @tooltip = 'Notification' and @aria-describedby = 'tooltip-16'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notify</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>bottom</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Notification</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip-16</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Featured Articles&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 text-right&quot;]/ir-header-icons[1]/ul[@class=&quot;actionSetting&quot;]/modal-email-alert[1]/li[@class=&quot;notify&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='Featured Articles']/div/div[2]/ir-header-icons/ul/modal-email-alert/li</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Articles'])[1]/following::li[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification'])[1]/preceding::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The 2019 Gender-Equality Index highlights 230 firms that are trailblazers ...'])[1]/preceding::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//modal-email-alert/li</value>
   </webElementXpaths>
</WebElementEntity>
